<?php

function aai_videos_theme($existing, $type, $theme, $path) {
	return array(
		'videos_recent' => array(
			'variables' => array(
				'pagehtml' => null,
				'data' => null,
			),
		),
		'videos_ranked_votes' => array(
			'variables' => array(
				'pagehtml' => null,
				'data' => null,
			),
		),
		'videos_ranked_views' => array(
			'variables' => array(
				'pagehtml' => null,
				'data' => null,
			),
		),
	);
}