<?php

/**
 * Implements hook_page_attachments().
 */
function aai_videos_page_attachments( array &$page ){
	$page['#attached']['library'][] = 'aai_videos/aai_videos_library';
}

/**
 * Implements hook_theme().
 */
function aai_videos_theme( $existing, $type, $theme, $path ) {
	return [
		'view_video' => [
			'variables' => [
				'pagehtml' => null,
				'data' => null,
			],
		],
		'videos_recent' => [
			'variables' => [
				'pagehtml' => null,
				'data' => null,
			],
		],
		'videos_ranked_votes' => [
			'variables' => [
				'pagehtml' => null,
				'data' => null,
			],
		],
		'videos_ranked_views' => [
			'variables' => [
				'pagehtml' => null,
				'data' => null,
			],
		],
	];
}