<?php

/**
 * Implements hook_theme().
 */
function aai_videos_theme( $existing, $type, $theme, $path ) {
	return [
		'videos_recent' => [
			'variables' => [
				'pagehtml' => null,
				'data' => null,
			],
		],
		'videos_ranked_votes' => [
			'variables' => [
				'pagehtml' => null,
				'data' => null,
			],
		],
		'videos_ranked_views' => [
			'variables' => [
				'pagehtml' => null,
				'data' => null,
			],
		],
	];
}