<?php
	define('AAI_API_KEY', 'ZyTesjx7mRRpFaFxMpCWgSD6');

	/**
	 * This is the main method used by the submodule to make the API calls.
	 * It checks that it was given a valid URL and method.
	 * @param  string $url    The API URL to hit
	 * @param  string $method The HTTP method to use in this API request
	 * @param  array  $params The parameters to pass in the request
	 * @return array          The response returned by the API
	 */
	function aai_api_response( $url, $method = 'GET', $params = [] ) {
		$methods = [
			'POST',
			'GET',
			'PUT',
			'DELETE'
		];
		$response = [];

		try {
			if ( empty( $url ) ) {
				throw new Exception( "Invalid url" );
			}
			if ( in_array( strtoupper( $method ), $methods ) === FALSE ) {
				throw new Exception( "Invalid method" );
			}
			else {

				switch ( strtoupper( $method ) ) {
					case 'GET':
					case 'POST':
					case 'PUT':
					case 'DELETE':
						$response = aai_api_call_request( $url, $method, $params );
						break;
					default:
						throw new Exception( "Invalid method" );
						break;
				}
			}
		}
		catch ( Exception $e ) {
			echo $e->getMessage();
		}

		return $response;
	}

	/**
	 * This is the method that actually sends the request to the API using curl
	 * @param  string $url    The API URL to hit
	 * @param  string $method The HTTP method to use in this API request
	 * @param  array  $params The parameters to pass in the request
	 * @return array          The response returned by the API
	 */
	function aai_api_call_request( $url, $method, $params = [] ) {
		try {

			// initialized curl
			$ch = curl_init();

			// set header for curl request
			$headers = [
				"Cache-Control: no-cache",
				"Pragma: no-cache",
				"X-Auth-Token: " . AAI_API_KEY
			];

			// set required setting with curl configuration
			curl_setopt( $ch, CURLOPT_URL, $url );
			curl_setopt( $ch, CURLOPT_HTTPHEADER, $headers );
			curl_setopt( $ch, CURLOPT_FRESH_CONNECT, TRUE );
			curl_setopt( $ch, CURLOPT_RETURNTRANSFER, TRUE );
			curl_setopt( $ch, CURLOPT_CUSTOMREQUEST, $method );
			curl_setopt( $ch, CURLOPT_FORBID_REUSE, 1 );

			// pass the additional values
			curl_setopt( $ch, CURLOPT_POSTFIELDS, http_build_query( $params ) );

			// close the curl connection
			$response = curl_exec( $ch );
			curl_close( $ch );

			return $response;
		}
		catch ( Exception $e ) {
			echo $e->getMessage();
		}
	}
